name: CI/CD

on: 
  push:
    branches: 
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install -r requirements.txt

      - name: Run Flake8
        run: |
          flake8 ./src --ignore=E501

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest ./src/tests

  iam:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read Terraform action from file
        id: read_action
        run: |
          ACTION=$(cat terraform_action.txt)
          echo "ACTION=${ACTION}" >> $GITHUB_ENV

      - name: Terraform Init and Apply/Destroy
        run: |
          cd infra/iam
          terraform init
          terraform plan
          if [ "${{ env.ACTION }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ env.ACTION }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified in terraform-action.txt"
            exit 1
          fi

  s3:
    if: github.ref == 'refs/heads/main'
    needs: iam
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read Terraform action from file
        id: read_action
        run: |
          ACTION=$(cat terraform_action.txt)
          echo "ACTION=${ACTION}" >> $GITHUB_ENV

      - name: Removing files from S3 bucket in case of destroy command
        run: |
          if [ "${{ env.ACTION }}" == "destroy" ]; then
            aws s3 rm s3://s3-bucket-ipea-eia366-pbrent366/ --recursive
          fi

      - name: Terraform Init and Apply/Destroy
        run: |
          cd infra/s3
          terraform init
          terraform plan
          if [ "${{ env.ACTION }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ env.ACTION }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified in terraform-action.txt"
            exit 1
          fi

  glue:
    if: github.ref == 'refs/heads/main'
    needs: s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read Terraform action from file
        id: read_action
        run: |
          ACTION=$(cat terraform_action.txt)
          echo "ACTION=${ACTION}" >> $GITHUB_ENV

      - name: Terraform Init and Apply/Destroy
        run: |
          cd infra/glue
          terraform init
          terraform plan
          if [ "${{ env.ACTION }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ env.ACTION }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified in terraform-action.txt"
            exit 1
          fi

      - name: Upload Python scripts to S3
        run: |
          if [ "${{ env.ACTION }}" == "apply" ]; then
            aws s3 cp src/etl/ s3://s3-bucket-ipea-eia366-pbrent366/scripts/ --recursive --exclude "*" --include "*.py"
          elif [ "${{ env.ACTION }}" == "destroy" ]; then
            aws s3 rm s3://s3-bucket-ipea-eia366-pbrent366/scripts/ --recursive --exclude "*" --include "*.py"
          fi

  ecr:
    if: github.ref == 'refs/heads/main'
    needs: iam
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read Terraform action from file
        id: read_action
        run: |
          ACTION=$(cat terraform_action.txt)
          echo "ACTION=${ACTION}" >> $GITHUB_ENV

      - name: Terraform Init and Apply/Destroy
        run: |
          cd infra/ecr
          terraform init
          terraform plan
          if [ "${{ env.ACTION }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ env.ACTION }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified in terraform-action.txt"
            exit 1
          fi
      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Build Docker image locally
        run: |
          if [ "${{ env.ACTION }}" == "apply" ]; then
            docker build -t 413467296690.dkr.ecr.us-east-1.amazonaws.com/ecr-ipea-eia366-pbrent366:latest -f ./Dockerfile .
          fi
  
      - name: Push Docker image to Amazon ECR
        run: |
          if [ "${{ env.ACTION }}" == "apply" ]; then
            docker push 413467296690.dkr.ecr.us-east-1.amazonaws.com/ecr-ipea-eia366-pbrent366:latest
          fi

  lambda:
    if: github.ref == 'refs/heads/main'
    needs: iam
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read Terraform action from file
        id: read_action
        run: |
          ACTION=$(cat terraform_action.txt)
          echo "ACTION=${ACTION}" >> $GITHUB_ENV

      - name: Zip Lambda function
        run: |
          cd src/lambda
          zip -r ../../infra/lambda/lambda_function.zip lambda_function.py
        working-directory: .

      - name: Terraform Init and Apply/Destroy
        run: |
          cd infra/lambda
          terraform init
          terraform plan
          if [ "${{ env.ACTION }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ env.ACTION }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified in terraform-action.txt"
            exit 1
          fi

  stepfunctions:
    if: github.ref == 'refs/heads/main'
    needs: [iam, s3, glue, ecr, lambda]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read Terraform action from file
        id: read_action
        run: |
          ACTION=$(cat terraform_action.txt)
          echo "ACTION=${ACTION}" >> $GITHUB_ENV

      - name: Terraform Init and Apply/Destroy
        run: |
          cd infra/stepfunctions
          terraform init
          terraform plan
          if [ "${{ env.ACTION }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ env.ACTION }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified in terraform-action.txt"
            exit 1
          fi